# Generated by Django 2.2.7 on 2019-11-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('address', models.CharField(default=None, max_length=200, verbose_name='Endereço')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=50)),
                ('neighborhood', models.CharField(default=None, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(default=None, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(default=None, max_length=2, verbose_name='UF')),
            ],
        ),
    ]
